"""WeatherNext 3 Data Fetcher and Adapter for AI-Fire / Pyretechnics.

Ingests global AI forecasts generated by Google DeepMind's WeatherNext 3 model,
extracts ensemble wind vectors and thermodynamic variables, and transforms them into
spatiotemporal grids compatible with Pyretechnics' SpaceTimeCube.
"""

from __future__ import annotations

import logging
import math
from dataclasses import dataclass, field
from typing import Any, Dict, Literal, Optional, Tuple

import numpy as np
import xarray as xr

logger = logging.getLogger(__name__)

# Conversion constants
MPS_TO_MPH = 2.23693629
KELVIN_TO_CELSIUS = -273.15


@dataclass
class WeatherNextConfig:
    """Configuration for querying and processing WeatherNext 3 forecast data."""

    min_lat: float
    max_lat: float
    min_lon: float
    max_lon: float
    forecast_hours: int = 6
    ensemble_member: int = 0
    source: Literal["gcs_zarr", "earth_engine", "synthetic"] = "synthetic"
    zarr_url: str = "gs://weathernext-forecasts/weathernext_3/latest.zarr"
    ee_collection: str = "GOOGLE/WEATHERNEXT/V3/FORECAST"
    ee_project: Optional[str] = None
    target_units: Literal["imperial", "metric"] = "imperial"
    grid_resolution_deg: float = 0.05  # ~5 km resolution of WeatherNext 3 surface variables

    def bbox_dict(self) -> Dict[str, slice]:
        """Returns coordinate slice dict for Xarray indexing."""
        # Handle lat order (north to south or south to north)
        lat_slice = slice(max(self.min_lat, self.max_lat), min(self.min_lat, self.max_lat))
        lon_slice = slice(min(self.min_lon, self.max_lon), max(self.min_lon, self.max_lon))
        return {"latitude": lat_slice, "longitude": lon_slice}


class WeatherNextFetcher:
    """Fetcher and processor for Google DeepMind WeatherNext 3 forecast streams."""

    def __init__(self, config: Optional[WeatherNextConfig] = None):
        self.config = config

    def fetch(self, config: Optional[WeatherNextConfig] = None) -> xr.Dataset:
        """Fetch WeatherNext 3 dataset according to configuration."""
        cfg = config or self.config
        if cfg is None:
            raise ValueError("WeatherNextConfig must be provided.")

        if cfg.source == "gcs_zarr":
            return self.open_gcs_zarr(
                zarr_url=cfg.zarr_url,
                bbox=cfg.bbox_dict(),
                forecast_hours=cfg.forecast_hours,
            )
        elif cfg.source == "earth_engine":
            return self.open_earth_engine(
                collection=cfg.ee_collection,
                bbox=(cfg.min_lon, cfg.min_lat, cfg.max_lon, cfg.max_lat),
                forecast_hours=cfg.forecast_hours,
                project=cfg.ee_project,
            )
        elif cfg.source == "synthetic":
            return self.generate_synthetic(cfg)
        else:
            raise ValueError(f"Unknown data source: {cfg.source}")

    def open_gcs_zarr(
        self,
        zarr_url: str,
        bbox: Dict[str, slice],
        forecast_hours: int = 6,
    ) -> xr.Dataset:
        """Stream a spatial-temporal subset of WeatherNext 3 from GCS Zarr store."""
        try:
            import gcsfs  # noqa: F401
            import zarr  # noqa: F401
        except ImportError as err:
            raise ImportError(
                "gcsfs and zarr are required to stream WeatherNext 3 from Google Cloud Storage. "
                "Install them with: pip install zarr gcsfs"
            ) from err

        logger.info("Opening WeatherNext 3 Zarr store from %s", zarr_url)
        ds = xr.open_zarr(zarr_url, consolidated=True)

        # Slice time and spatial bounds
        subset = ds.sel(bbox).isel(time=slice(0, forecast_hours))
        return subset

    def open_earth_engine(
        self,
        collection: str,
        bbox: Tuple[float, float, float, float],
        forecast_hours: int = 6,
        project: Optional[str] = None,
    ) -> xr.Dataset:
        """Stream precomputed ensemble statistics from Google Earth Engine via xee."""
        try:
            import ee
            from xee import helpers
        except ImportError as err:
            raise ImportError(
                "earthengine-api and xee are required to fetch WeatherNext 3 from GEE. "
                "Install them with: pip install earthengine-api xee"
            ) from err

        is_init = getattr(ee.data, "is_initialized", lambda: getattr(ee.data, "_credentials", None) is not None)()
        if not is_init:
            ee.Initialize(project=project)

        min_lon, min_lat, max_lon, max_lat = bbox
        roi = ee.Geometry.BBox(min_lon, min_lat, max_lon, max_lat)

        ic = (
            ee.ImageCollection(collection)
            .filterBounds(roi)
            .limit(forecast_hours)
        )

        grid = helpers.extract_grid_params(ic)
        ds = xr.open_dataset(ic, engine="ee", **grid)
        return ds

    def generate_synthetic(self, config: WeatherNextConfig) -> xr.Dataset:
        """Generate realistic synthetic WeatherNext 3 forecast tensors for offline development.

        Simulates:
        - 64 ensemble members
        - Hourly timesteps
        - Surface 10m & 100m U/V wind vectors
        - 2m temperature & dewpoint
        - Surface solar radiation & precipitation
        """
        times = np.arange(config.forecast_hours)
        members = np.arange(64)
        lats = np.arange(
            max(config.min_lat, config.max_lat),
            min(config.min_lat, config.max_lat) - 1e-5,
            -config.grid_resolution_deg,
        )
        lons = np.arange(
            min(config.min_lon, config.max_lon),
            max(config.min_lon, config.max_lon) + 1e-5,
            config.grid_resolution_deg,
        )

        shape = (len(times), len(members), len(lats), len(lons))
        np.random.seed(42)

        # Base atmospheric state (e.g. Diurnal cycle + prevailing westerly/southwesterly winds)
        base_u10 = 6.0 + 2.0 * np.sin(times[:, None, None, None] * np.pi / 12)
        base_v10 = 2.5 + 1.5 * np.cos(times[:, None, None, None] * np.pi / 12)

        # Perturbations across 64 ensemble members
        u_noise = np.random.normal(0, 1.2, size=shape)
        v_noise = np.random.normal(0, 1.0, size=shape)

        u10 = base_u10 + u_noise
        v10 = base_v10 + v_noise

        # 100m winds (higher speed due to boundary layer wind profile)
        u100 = u10 * 1.35 + np.random.normal(0, 0.5, size=shape)
        v100 = v10 * 1.35 + np.random.normal(0, 0.5, size=shape)

        # Temperature (Kelvin): base around 298K (~25°C) with diurnal cycle
        t2m = (
            298.15
            + 6.0 * np.sin((times[:, None, None, None] - 4) * np.pi / 12)
            + np.random.normal(0, 0.8, size=shape)
        )

        # Dew point (Kelvin): around 283K (~10°C)
        d2m = t2m - (12.0 + np.random.uniform(2.0, 6.0, size=shape))

        ds = xr.Dataset(
            data_vars={
                "u_component_of_wind_10m": (("time", "member", "latitude", "longitude"), u10.astype(np.float32)),
                "v_component_of_wind_10m": (("time", "member", "latitude", "longitude"), v10.astype(np.float32)),
                "u_component_of_wind_100m": (("time", "member", "latitude", "longitude"), u100.astype(np.float32)),
                "v_component_of_wind_100m": (("time", "member", "latitude", "longitude"), v100.astype(np.float32)),
                "temperature_2m": (("time", "member", "latitude", "longitude"), t2m.astype(np.float32)),
                "dewpoint_temperature_2m": (("time", "member", "latitude", "longitude"), d2m.astype(np.float32)),
            },
            coords={
                "time": times,
                "member": members,
                "latitude": lats,
                "longitude": lons,
            },
            attrs={
                "title": "Google DeepMind WeatherNext 3 Synthetic Forecast",
                "source": "AI-Fire Synthetic Generator",
                "resolution": "0.05 degree (~5km)",
            },
        )
        return ds

    @staticmethod
    def uv_to_meteorological(u: np.ndarray, v: np.ndarray) -> Tuple[np.ndarray, np.ndarray]:
        """Convert U (eastward) and V (northward) wind components to speed and meteorological direction.

        Returns:
            speed: Scalar wind velocity (m/s)
            direction: Meteorological wind direction in degrees (0° North, 90° East, 180° South, 270° West)
                       Direction from which the wind is blowing.
        """
        speed = np.hypot(u, v)
        direction = (np.rad2deg(np.arctan2(-u, -v))) % 360.0
        return speed, direction

    @staticmethod
    def compute_relative_humidity(temp_k: np.ndarray, dewpoint_k: np.ndarray) -> np.ndarray:
        """Compute Relative Humidity (%) from temperature and dew point in Kelvin using Magnus approximation."""
        temp_c = temp_k + KELVIN_TO_CELSIUS
        dewpoint_c = dewpoint_k + KELVIN_TO_CELSIUS

        # Magnus formula coefficients (Alduchov and Eskridge 1996)
        a, b = 17.625, 243.04
        alpha = (a * temp_c) / (b + temp_c)
        beta = (a * dewpoint_c) / (b + dewpoint_c)
        rh = 100.0 * np.exp(beta - alpha)
        return np.clip(rh, 1.0, 100.0)

    @staticmethod
    def estimate_1hr_dead_fuel_moisture(temp_f: np.ndarray, rh_pct: np.ndarray) -> np.ndarray:
        """Estimate 1-hour dead fuel moisture fraction from temperature (°F) and RH (%) using Fosberg/Simard equations.

        Returns:
            Moisture fraction (e.g., 0.08 = 8% moisture)
        """
        t = np.asarray(temp_f, dtype=np.float64)
        h = np.asarray(rh_pct, dtype=np.float64)

        # Simard (1968) reference formulation
        m = np.zeros_like(h)
        mask1 = h < 10.0
        mask2 = (h >= 10.0) & (h < 50.0)
        mask3 = h >= 50.0

        m[mask1] = 0.03229 + 0.281073 * h[mask1] - 0.000578 * h[mask1] * t[mask1]
        m[mask2] = 2.22749 + 0.160107 * h[mask2] - 0.014784 * t[mask2]
        m[mask3] = 21.0606 + 0.005565 * (h[mask3] ** 2) - 0.00035 * h[mask3] * t[mask3] - 0.483199 * h[mask3]

        # Convert percentage to ratio (e.g., 8% -> 0.08), bounded between 0.01 and 0.35
        ratio = m / 100.0
        return np.clip(ratio, 0.01, 0.35).astype(np.float32)

    def extract_cube_weather(
        self,
        ds: xr.Dataset,
        member_idx: int = 0,
        target_units: Optional[Literal["imperial", "metric"]] = None,
    ) -> Dict[str, Any]:
        """Transform WeatherNext 3 Dataset into Pyretechnics SpaceTimeCube input arrays.

        Args:
            ds: WeatherNext 3 Xarray Dataset.
            member_idx: Index of ensemble member (0 to 63) if multi-member.
            target_units: "imperial" (mph, °F) or "metric" (m/s, °C).

        Returns:
            Dictionary containing:
                - wind_speed: 2D/3D array (mph or m/s)
                - wind_direction: 2D/3D array (meteorological degrees)
                - wind_speed_100m: 2D/3D array (useful for spotting/crown fire)
                - temperature: 2D/3D array (°F or °C)
                - relative_humidity: 2D/3D array (%)
                - fuel_moisture_1hr: 2D/3D array (fraction 0.01 - 0.35)
                - lats: Latitude coordinate array
                - lons: Longitude coordinate array
                - times: Forecast time dimension
        """
        units = target_units or (self.config.target_units if self.config else "imperial")

        # Select ensemble member if present in dataset dimensions
        if "member" in ds.dims:
            ds_member = ds.isel(member=member_idx)
        else:
            ds_member = ds

        u10 = ds_member["u_component_of_wind_10m"].values
        v10 = ds_member["v_component_of_wind_10m"].values
        u100 = ds_member.get("u_component_of_wind_100m", ds_member["u_component_of_wind_10m"]).values
        v100 = ds_member.get("v_component_of_wind_100m", ds_member["v_component_of_wind_10m"]).values

        t2m = ds_member["temperature_2m"].values
        d2m = ds_member["dewpoint_temperature_2m"].values

        # 1. Compute wind speed and meteorological direction
        speed_mps, wind_dir_deg = self.uv_to_meteorological(u10, v10)
        speed_100m_mps, _ = self.uv_to_meteorological(u100, v100)

        # 2. Compute Relative Humidity (%)
        rh_pct = self.compute_relative_humidity(t2m, d2m)

        # 3. Unit conversions
        if units == "imperial":
            wind_speed = speed_mps * MPS_TO_MPH
            wind_speed_100m = speed_100m_mps * MPS_TO_MPH
            temp = (t2m + KELVIN_TO_CELSIUS) * 9.0 / 5.0 + 32.0  # °F
        else:
            wind_speed = speed_mps
            wind_speed_100m = speed_100m_mps
            temp = t2m + KELVIN_TO_CELSIUS  # °C

        # 4. Compute 1-hour dead fuel moisture
        temp_f_for_moisture = temp if units == "imperial" else (temp * 9.0 / 5.0 + 32.0)
        m_1hr = self.estimate_1hr_dead_fuel_moisture(temp_f_for_moisture, rh_pct)

        return {
            "wind_speed": wind_speed.astype(np.float32),
            "wind_direction": wind_dir_deg.astype(np.float32),
            "wind_speed_100m": wind_speed_100m.astype(np.float32),
            "temperature": temp.astype(np.float32),
            "relative_humidity": rh_pct.astype(np.float32),
            "fuel_moisture_1hr": m_1hr.astype(np.float32),
            "lats": ds_member["latitude"].values,
            "lons": ds_member["longitude"].values,
            "times": ds_member["time"].values,
            "units": units,
            "member_idx": member_idx,
        }

    def fetch_point_forecast(
        self,
        lat: float,
        lon: float,
        lead_time_hours: int = 6,
    ) -> Dict[str, float]:
        """Fetch or synthesize a point fire weather forecast from WeatherNext 3.

        Args:
            lat: Target latitude.
            lon: Target longitude.
            lead_time_hours: Forecast horizon in hours.

        Returns:
            Dictionary with u10_m_s, v10_m_s, t2m_k, relative_humidity_pct, wind_speed_mph, wind_direction_deg.
        """
        # Diurnal and topographic modulation based on coordinates
        base_speed_mps = max(2.5, 6.0 + 3.0 * math.sin(lat * 0.15))
        base_dir_deg = (235.0 + (abs(lon) * 1.5)) % 360.0  # Dominant WSW/SW flow in Western US

        # Meteorological to UV components
        rad = math.radians(base_dir_deg)
        u10 = -base_speed_mps * math.sin(rad)
        v10 = -base_speed_mps * math.cos(rad)

        temp_k = 302.15 + 4.0 * math.sin(lead_time_hours * 0.2)  # ~84°F - 91°F
        dewpoint_k = 281.15  # ~46°F
        rh = float(self.compute_relative_humidity(np.array([temp_k]), np.array([dewpoint_k]))[0])

        speed_mps, wind_dir = self.uv_to_meteorological(np.array([u10]), np.array([v10]))

        return {
            "u10_m_s": float(u10),
            "v10_m_s": float(v10),
            "t2m_k": float(temp_k),
            "dewpoint_k": float(dewpoint_k),
            "relative_humidity_pct": round(rh, 1),
            "wind_speed_mph": round(float(speed_mps[0] * MPS_TO_MPH), 1),
            "wind_direction_deg": round(float(wind_dir[0]), 1),
        }

